package com.company.employeemanagement.entity;

public enum AuditAction {
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_DELETED,
    LOGIN,
    LOGOUT,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    TASK_DELETED,
    DAILY_WORK_SUBMITTED,
    LEAVE_APPLIED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED
}
